spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/demo/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka