spring:
  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: demo-service
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true